/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;

import javax.net.ssl.HttpsURLConnection;

public class App {
    public static void main(String[] args) throws Exception {
        
        String httpsURL = "https://www.bizinfo.go.kr/uss/rss/bizinfoApi.do?crtfcKey=8T71sG&dataType=json&searchLclasId=all&searchPldirJrsdCode=all&searchIndustCode=all&searchAreaCode=all";
        URL myUrl = new URL(httpsURL);
        HttpsURLConnection conn = (HttpsURLConnection)myUrl.openConnection();
        InputStream is = conn.getInputStream();
        InputStreamReader isr = new InputStreamReader(is);
        BufferedReader br = new BufferedReader(isr);

        String inputLine;
        System.out.println("http request read");
        while ((inputLine = br.readLine()) != null) {
            System.out.println(inputLine);
        }
    }
}
